/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Presentacion;

import Datos.vcarro;
import Logica.fcarro;
import java.awt.Color;
import java.awt.MouseInfo;
import java.awt.Point;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Pc01
 */
public class fmCarro extends javax.swing.JFrame {

    private int x;
    private int y;
    
    public fmCarro() {
        initComponents();
        mostrar("");
        habilitar();
        this.getContentPane().setBackground(Color.decode("#fafafa"));
        jPanel1.setBackground(Color.decode("#c62828"));
        jPanel2.setBackground(Color.decode("#ff6659"));
        jPanel3.setBackground(Color.decode("#9a0007"));
        jButton1.setBackground(Color.decode("#c62828"));
        btnuevo.setBackground(Color.decode("#c62828"));
        jButton7.setBackground(Color.decode("#c62828"));
        btneliminar.setBackground(Color.decode("#c62828"));
        btguardar.setBackground(Color.decode("#c62828"));
        btcancelar.setBackground(Color.decode("#c62828"));
    }
    
    private String accion="guardar";
    
    void ocultar_columnas(){
        tablalistado.getColumnModel().getColumn(0).setMaxWidth(0);
        tablalistado.getColumnModel().getColumn(0).setMinWidth(0);
        tablalistado.getColumnModel().getColumn(0).setPreferredWidth(0);
    }
    
    void habilitar(){
        txtidecarro.setVisible(false);
        
        txtPlaca.setEnabled(true);
        txtMarca.setEnabled(true);
        txtModelo.setEnabled(true);
        txtMotor.setEnabled(true);
        txtCilindro.setEnabled(true);
        txtColor.setEnabled(true);
        txtAnio.setEnabled(true);
        txtPuerta.setEnabled(true);
        JTipo.setEnabled(true);
        JEstado.setEnabled(true);
        btguardar.setEnabled(true);
        btcancelar.setEnabled(true); 
        btnuevo.setEnabled(true);

    }
    
       void inhabilitar(){
        
        txtPlaca.setEnabled(false);
        txtMarca.setEnabled(false);
        txtModelo.setEnabled(false);
        txtMotor.setEnabled(false);
        txtCilindro.setEnabled(false);
        txtColor.setEnabled(false);
        txtAnio.setEnabled(false);
        txtPuerta.setEnabled(false);
        JTipo.setEnabled(false);
        JEstado.setEnabled(false);
      

    }
    
    
    
    void mostrar (String buscar){
        try {
            DefaultTableModel modelo;
            fcarro func = new fcarro();
            modelo = func.mostrar(buscar);
            
            tablalistado.setModel(modelo);
            ocultar_columnas();
            lbltotalregistros.setText("Total Registros "+Integer.toString(func.totalregistros));
        } catch (Exception e) {
            JOptionPane.showConfirmDialog(rootPane, e);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        btnuevo = new javax.swing.JButton();
        btguardar = new javax.swing.JButton();
        btcancelar = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        JPlaca1 = new javax.swing.JLabel();
        txtbuscar = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        btneliminar = new javax.swing.JButton();
        lbltotalregistros = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablalistado = new javax.swing.JTable();
        JPlaca = new javax.swing.JLabel();
        txtPlaca = new javax.swing.JTextField();
        JMarca = new javax.swing.JLabel();
        txtMarca = new javax.swing.JTextField();
        JMotor = new javax.swing.JLabel();
        txtModelo = new javax.swing.JTextField();
        JModelo = new javax.swing.JLabel();
        txtCilindro = new javax.swing.JTextField();
        JTexto5 = new javax.swing.JLabel();
        txtMotor = new javax.swing.JTextField();
        JTexto6 = new javax.swing.JLabel();
        txtColor = new javax.swing.JTextField();
        JTexto7 = new javax.swing.JLabel();
        JTipo = new javax.swing.JComboBox<>();
        JTexto8 = new javax.swing.JLabel();
        txtAnio = new javax.swing.JTextField();
        txtPrecio = new javax.swing.JTextField();
        JTexto9 = new javax.swing.JLabel();
        JTexto10 = new javax.swing.JLabel();
        JEstado = new javax.swing.JComboBox<>();
        JTexto11 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtdesc = new javax.swing.JTextArea();
        JTexto12 = new javax.swing.JLabel();
        txtPuerta = new javax.swing.JTextField();
        txtidecarro = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1100, 870));
        setUndecorated(true);
        setPreferredSize(new java.awt.Dimension(430, 870));
        addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                formMouseDragged(evt);
            }
        });
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                formMousePressed(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(102, 102, 102));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 36, Short.MAX_VALUE)
        );

        btnuevo.setBackground(new java.awt.Color(255, 255, 255));
        btnuevo.setFont(new java.awt.Font("SansSerif", 0, 24)); // NOI18N
        btnuevo.setForeground(new java.awt.Color(255, 255, 255));
        btnuevo.setText("Nuevo");
        btnuevo.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));
        btnuevo.setBorderPainted(false);
        btnuevo.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnuevo.setDefaultCapable(false);
        btnuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnuevoActionPerformed(evt);
            }
        });

        btguardar.setBackground(new java.awt.Color(255, 255, 255));
        btguardar.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        btguardar.setForeground(new java.awt.Color(255, 255, 255));
        btguardar.setText("Guardar");
        btguardar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        btguardar.setBorderPainted(false);
        btguardar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btguardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btguardarActionPerformed(evt);
            }
        });

        btcancelar.setBackground(new java.awt.Color(255, 255, 255));
        btcancelar.setFont(new java.awt.Font("SansSerif", 0, 22)); // NOI18N
        btcancelar.setForeground(new java.awt.Color(255, 255, 255));
        btcancelar.setText("Cancelar");
        btcancelar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(btnuevo, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btguardar, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btcancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(667, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnuevo, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btguardar, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btcancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 19, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1100, -1));

        jPanel2.setPreferredSize(new java.awt.Dimension(590, 900));

        JPlaca1.setFont(new java.awt.Font("SansSerif", 0, 24)); // NOI18N
        JPlaca1.setForeground(new java.awt.Color(51, 51, 51));
        JPlaca1.setText("Buscar");

        txtbuscar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        txtbuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtbuscarActionPerformed(evt);
            }
        });

        jButton1.setBackground(new java.awt.Color(255, 255, 255));
        jButton1.setFont(new java.awt.Font("SansSerif", 0, 22)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Buscar");
        jButton1.setToolTipText("");
        jButton1.setBorderPainted(false);
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton7.setBackground(new java.awt.Color(255, 255, 255));
        jButton7.setFont(new java.awt.Font("SansSerif", 0, 22)); // NOI18N
        jButton7.setForeground(new java.awt.Color(255, 255, 255));
        jButton7.setText("Salir");
        jButton7.setBorderPainted(false);
        jButton7.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        btneliminar.setBackground(new java.awt.Color(255, 255, 255));
        btneliminar.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        btneliminar.setForeground(new java.awt.Color(255, 255, 255));
        btneliminar.setText("Eliminar");
        btneliminar.setBorderPainted(false);
        btneliminar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btneliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btneliminarActionPerformed(evt);
            }
        });

        lbltotalregistros.setText("Registros");

        tablalistado.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tablalistado.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablalistadoMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tablalistado);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jScrollPane1)
                        .addContainerGap())
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(lbltotalregistros, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(JPlaca1, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtbuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btneliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(21, 21, 21))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addComponent(JPlaca1, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtbuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGap(0, 0, 0)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btneliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(21, 21, 21)))
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 544, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lbltotalregistros, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(169, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 126, 590, 870));

        JPlaca.setFont(new java.awt.Font("SansSerif", 0, 24)); // NOI18N
        JPlaca.setForeground(new java.awt.Color(102, 102, 102));
        JPlaca.setText("Placa");
        getContentPane().add(JPlaca, new org.netbeans.lib.awtextra.AbsoluteConstraints(32, 205, 84, 28));

        txtPlaca.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        txtPlaca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPlacaActionPerformed(evt);
            }
        });
        getContentPane().add(txtPlaca, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 210, 179, 28));

        JMarca.setFont(new java.awt.Font("SansSerif", 0, 24)); // NOI18N
        JMarca.setForeground(new java.awt.Color(102, 102, 102));
        JMarca.setText("Marca");
        getContentPane().add(JMarca, new org.netbeans.lib.awtextra.AbsoluteConstraints(32, 251, 84, 28));

        txtMarca.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        txtMarca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMarcaActionPerformed(evt);
            }
        });
        getContentPane().add(txtMarca, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 251, 179, 28));

        JMotor.setFont(new java.awt.Font("SansSerif", 0, 24)); // NOI18N
        JMotor.setForeground(new java.awt.Color(102, 102, 102));
        JMotor.setText("Motor");
        getContentPane().add(JMotor, new org.netbeans.lib.awtextra.AbsoluteConstraints(32, 343, 84, 28));

        txtModelo.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        txtModelo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtModeloActionPerformed(evt);
            }
        });
        getContentPane().add(txtModelo, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 297, 179, 28));

        JModelo.setFont(new java.awt.Font("SansSerif", 0, 24)); // NOI18N
        JModelo.setForeground(new java.awt.Color(102, 102, 102));
        JModelo.setText("Modelo");
        getContentPane().add(JModelo, new org.netbeans.lib.awtextra.AbsoluteConstraints(32, 297, 84, 28));

        txtCilindro.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        txtCilindro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCilindroActionPerformed(evt);
            }
        });
        getContentPane().add(txtCilindro, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 389, 179, 32));

        JTexto5.setFont(new java.awt.Font("SansSerif", 0, 24)); // NOI18N
        JTexto5.setForeground(new java.awt.Color(102, 102, 102));
        JTexto5.setText("Cilindro");
        getContentPane().add(JTexto5, new org.netbeans.lib.awtextra.AbsoluteConstraints(32, 389, -1, -1));

        txtMotor.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        txtMotor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMotorActionPerformed(evt);
            }
        });
        getContentPane().add(txtMotor, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 343, 179, 28));

        JTexto6.setFont(new java.awt.Font("SansSerif", 0, 24)); // NOI18N
        JTexto6.setForeground(new java.awt.Color(102, 102, 102));
        JTexto6.setText("Color");
        getContentPane().add(JTexto6, new org.netbeans.lib.awtextra.AbsoluteConstraints(32, 439, -1, -1));

        txtColor.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        txtColor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtColorActionPerformed(evt);
            }
        });
        getContentPane().add(txtColor, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 439, 179, 32));

        JTexto7.setFont(new java.awt.Font("SansSerif", 0, 24)); // NOI18N
        JTexto7.setForeground(new java.awt.Color(102, 102, 102));
        JTexto7.setText("Puertas");
        getContentPane().add(JTexto7, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 540, -1, -1));

        JTipo.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        JTipo.setForeground(new java.awt.Color(102, 102, 102));
        JTipo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Mecanico", "Automatico" }));
        JTipo.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 102)));
        JTipo.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        JTipo.setLightWeightPopupEnabled(false);
        JTipo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JTipoActionPerformed(evt);
            }
        });
        getContentPane().add(JTipo, new org.netbeans.lib.awtextra.AbsoluteConstraints(119, 595, 179, 30));

        JTexto8.setFont(new java.awt.Font("SansSerif", 0, 24)); // NOI18N
        JTexto8.setForeground(new java.awt.Color(102, 102, 102));
        JTexto8.setText("Año");
        getContentPane().add(JTexto8, new org.netbeans.lib.awtextra.AbsoluteConstraints(32, 489, -1, -1));

        txtAnio.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        txtAnio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAnioActionPerformed(evt);
            }
        });
        getContentPane().add(txtAnio, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 489, 179, 30));

        txtPrecio.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        txtPrecio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPrecioActionPerformed(evt);
            }
        });
        getContentPane().add(txtPrecio, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 700, 179, 32));

        JTexto9.setFont(new java.awt.Font("SansSerif", 0, 24)); // NOI18N
        JTexto9.setForeground(new java.awt.Color(102, 102, 102));
        JTexto9.setText("Tipo");
        getContentPane().add(JTexto9, new org.netbeans.lib.awtextra.AbsoluteConstraints(32, 595, -1, -1));

        JTexto10.setFont(new java.awt.Font("SansSerif", 0, 24)); // NOI18N
        JTexto10.setForeground(new java.awt.Color(102, 102, 102));
        JTexto10.setText("Precio");
        getContentPane().add(JTexto10, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 700, -1, 39));

        JEstado.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        JEstado.setForeground(new java.awt.Color(102, 102, 102));
        JEstado.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Disponible", "Vendido" }));
        JEstado.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 102)));
        JEstado.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        JEstado.setLightWeightPopupEnabled(false);
        JEstado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JEstadoActionPerformed(evt);
            }
        });
        getContentPane().add(JEstado, new org.netbeans.lib.awtextra.AbsoluteConstraints(119, 645, 179, 39));

        JTexto11.setFont(new java.awt.Font("SansSerif", 0, 24)); // NOI18N
        JTexto11.setForeground(new java.awt.Color(102, 102, 102));
        JTexto11.setText("Descripcion");
        getContentPane().add(JTexto11, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 750, 130, 40));

        txtdesc.setColumns(20);
        txtdesc.setRows(5);
        jScrollPane2.setViewportView(txtdesc);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 750, 284, 90));

        JTexto12.setFont(new java.awt.Font("SansSerif", 0, 24)); // NOI18N
        JTexto12.setForeground(new java.awt.Color(102, 102, 102));
        JTexto12.setText("Estado");
        getContentPane().add(JTexto12, new org.netbeans.lib.awtextra.AbsoluteConstraints(32, 645, -1, 39));

        txtPuerta.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        txtPuerta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPuertaActionPerformed(evt);
            }
        });
        getContentPane().add(txtPuerta, new org.netbeans.lib.awtextra.AbsoluteConstraints(119, 545, 179, 32));

        txtidecarro.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        txtidecarro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtidecarroActionPerformed(evt);
            }
        });
        getContentPane().add(txtidecarro, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 180, 179, 28));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMousePressed
         x = evt.getX();
         y = evt.getY();
    }//GEN-LAST:event_formMousePressed

    private void formMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseDragged
        Point ubicacion = MouseInfo.getPointerInfo().getLocation();//1
        System.out.println("Coordenadas: ("+ubicacion.x+","+ubicacion.y+")");//2
        setLocation(ubicacion.x - x, ubicacion.y - y);//3
    }//GEN-LAST:event_formMouseDragged

    private void txtPlacaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPlacaActionPerformed
        // TODO add your handling code here:
        txtPlaca.transferFocus();
    }//GEN-LAST:event_txtPlacaActionPerformed

    private void txtMarcaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMarcaActionPerformed
        // TODO add your handling code here:
        txtMarca.transferFocus();
    }//GEN-LAST:event_txtMarcaActionPerformed

    private void txtModeloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtModeloActionPerformed
        // TODO add your handling code here:
        txtModelo.transferFocus();
    }//GEN-LAST:event_txtModeloActionPerformed

    private void txtCilindroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCilindroActionPerformed
        // TODO add your handling code here:
        txtCilindro.transferFocus();
    }//GEN-LAST:event_txtCilindroActionPerformed

    private void txtMotorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMotorActionPerformed
        // TODO add your handling code here:
        txtMotor.transferFocus();
    }//GEN-LAST:event_txtMotorActionPerformed

    private void txtColorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtColorActionPerformed
        // TODO add your handling code here:
        txtColor.transferFocus();
    }//GEN-LAST:event_txtColorActionPerformed

    private void txtAnioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAnioActionPerformed
        // TODO add your handling code here:
        txtAnio.transferFocus();
    }//GEN-LAST:event_txtAnioActionPerformed

    private void txtPrecioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPrecioActionPerformed
        // TODO add your handling code here:
        txtPrecio.transferFocus();
    }//GEN-LAST:event_txtPrecioActionPerformed

    private void txtbuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtbuscarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtbuscarActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // BOTON BUSCAR
        mostrar(txtbuscar.getText());
    }//GEN-LAST:event_jButton1ActionPerformed

    private void btneliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btneliminarActionPerformed
        if(txtidecarro.getText().equals("")){
            int confirmacion = JOptionPane.showConfirmDialog(rootPane, "Estas seguro de eliminar el carro");
            if(confirmacion == 0){
                fcarro func = new fcarro();
                vcarro dts = new vcarro();
                
                dts.setIdcarro(Integer.parseInt(txtidecarro.getText()));
                func.eliminar(dts);
                mostrar("");
                inhabilitar();
            }
        }
    }//GEN-LAST:event_btneliminarActionPerformed

    private void txtPuertaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPuertaActionPerformed
        // TODO add your handling code here:
        txtPuerta.transferFocus();
    }//GEN-LAST:event_txtPuertaActionPerformed

    private void btnuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnuevoActionPerformed
        habilitar();
        btguardar.setText("Guardar");
        accion="guardar";
        txtPlaca.setText("");
        txtMarca.setText("");
        txtModelo.setText("");
        txtMotor.setText("");
        txtCilindro.setText("");
        txtColor.setText("");
        txtAnio.setText("");
        txtPuerta.setText("");
        txtPrecio.setText("");
        txtdesc.setText("");
        
    }//GEN-LAST:event_btnuevoActionPerformed

    private void btguardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btguardarActionPerformed
        // TODO add your handling code here:
        if(txtPlaca.getText().length()==0){
            JOptionPane.showConfirmDialog(rootPane, "Debes ingresar placa del vehiculo");
            txtPlaca.requestFocus();
            return;
        }
        if(txtMarca.getText().length()==0){
            JOptionPane.showConfirmDialog(rootPane, "Debes ingresar marca del vehiculo");
            txtMarca.requestFocus();
            return;
        }
        if(txtModelo.getText().length()==0){
            JOptionPane.showConfirmDialog(rootPane, "Debes ingresar modelo del vehiculo");
            txtModelo.requestFocus();
            return;
        }
        if(txtMotor.getText().length()==0){
            JOptionPane.showConfirmDialog(rootPane, "Debes ingresar motor del vehiculo");
            txtMotor.requestFocus();
            return;
        }
        if(txtCilindro.getText().length()==0){
            JOptionPane.showConfirmDialog(rootPane, "Debes ingresar cilindro del vehiculo");
            txtCilindro.requestFocus();
            return;
        }
        if(txtColor.getText().length()==0){
            JOptionPane.showConfirmDialog(rootPane, "Debes ingresar color del vehiculo");
            txtColor.requestFocus();
            return;
        }
        if(txtAnio.getText().length()==0){
            JOptionPane.showConfirmDialog(rootPane, "Debes ingresar año del vehiculo");
            txtAnio.requestFocus();
            return;
        }
        if(txtPuerta.getText().length()==0){
            JOptionPane.showConfirmDialog(rootPane, "Debes ingresar el numero de puertas del vehiculo");
            txtPuerta.requestFocus();
            return;
        }
        if(txtPrecio.getText().length()==0){
            JOptionPane.showConfirmDialog(rootPane, "Debes ingresar el numero de puertas del vehiculo");
            txtPrecio.requestFocus();
            return;
        }
        vcarro dts = new vcarro();
        fcarro func = new fcarro();
        
        dts.setPlaca(txtPlaca.getText());
        dts.setMarca(txtMarca.getText());
        dts.setModelo(txtModelo.getText());
        dts.setMotor(Double.parseDouble(txtMotor.getText()));
        dts.setCilindro(Integer.parseInt(txtCilindro.getText()));
        dts.setColor(txtColor.getText());
        dts.setAnio(Integer.parseInt(txtAnio.getText()));
        dts.setPuertas(Integer.parseInt(txtPuerta.getText()));
        
        int seleccionado = JTipo.getSelectedIndex();
        dts.setTipo((String) JTipo.getItemAt(seleccionado));
        
        seleccionado = JEstado.getSelectedIndex();
        dts.setEstado((String) JEstado.getItemAt(seleccionado));
        
        dts.setPrecio(Double.parseDouble(txtPrecio.getText()));
        dts.setDescripcion(txtdesc.getText());
        
        
        
        if(accion.equals("guardar")){
            if(func.insertar(dts)){
                JOptionPane.showMessageDialog(rootPane, "El carro fue registrado exitosamente");
                mostrar("");
                inhabilitar();
            }
            
        }else if(accion.equals("editar")){
            dts.setIdcarro(Integer.parseInt(txtidecarro.getText()));
            
            if(func.editar(dts)){
                JOptionPane.showMessageDialog(rootPane, "El carro fue editado exitosamente");
                mostrar("");
                inhabilitar();
            }
        }
        
        
    }//GEN-LAST:event_btguardarActionPerformed

    private void txtidecarroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtidecarroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtidecarroActionPerformed

    private void JTipoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JTipoActionPerformed
        // TODO add your handling code here:
        JTipo.transferFocus();
    }//GEN-LAST:event_JTipoActionPerformed

    private void JEstadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JEstadoActionPerformed
        // TODO add your handling code here:
        JEstado.transferFocus();
    }//GEN-LAST:event_JEstadoActionPerformed

    private void tablalistadoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablalistadoMouseClicked
        // TODO add your handling code here:
        btguardar.setText("Editar");
        habilitar();
        btneliminar.setEnabled(true);
        accion="editar";
        
        int fila = tablalistado.rowAtPoint(evt.getPoint());
        txtidecarro.setText(tablalistado.getValueAt(fila, 0).toString());
        
        txtPlaca.setText(tablalistado.getValueAt(fila, 1).toString());
        txtMarca.setText(tablalistado.getValueAt(fila, 1).toString());
        txtModelo.setText(tablalistado.getValueAt(fila, 3).toString());
        txtMotor.setText(tablalistado.getValueAt(fila, 4).toString());
        txtCilindro.setText(tablalistado.getValueAt(fila, 5).toString());
        txtColor.setText(tablalistado.getValueAt(fila, 6).toString());
        txtAnio.setText(tablalistado.getValueAt(fila, 7).toString());
        txtPuerta.setText(tablalistado.getValueAt(fila, 8).toString());
        JTipo.setSelectedItem(tablalistado.getValueAt(fila, 9).toString());
        JEstado.setSelectedItem(tablalistado.getValueAt(fila, 10).toString());
        txtPrecio.setText(tablalistado.getValueAt(fila, 11).toString());
        txtdesc.setText(tablalistado.getValueAt(fila, 12).toString());
        
    }//GEN-LAST:event_tablalistadoMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(fmCarro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(fmCarro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(fmCarro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(fmCarro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new fmCarro().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> JEstado;
    private javax.swing.JLabel JMarca;
    private javax.swing.JLabel JModelo;
    private javax.swing.JLabel JMotor;
    private javax.swing.JLabel JPlaca;
    private javax.swing.JLabel JPlaca1;
    private javax.swing.JLabel JTexto10;
    private javax.swing.JLabel JTexto11;
    private javax.swing.JLabel JTexto12;
    private javax.swing.JLabel JTexto5;
    private javax.swing.JLabel JTexto6;
    private javax.swing.JLabel JTexto7;
    private javax.swing.JLabel JTexto8;
    private javax.swing.JLabel JTexto9;
    private javax.swing.JComboBox<String> JTipo;
    private javax.swing.JButton btcancelar;
    private javax.swing.JButton btguardar;
    private javax.swing.JButton btneliminar;
    private javax.swing.JButton btnuevo;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lbltotalregistros;
    private javax.swing.JTable tablalistado;
    private javax.swing.JTextField txtAnio;
    private javax.swing.JTextField txtCilindro;
    private javax.swing.JTextField txtColor;
    private javax.swing.JTextField txtMarca;
    private javax.swing.JTextField txtModelo;
    private javax.swing.JTextField txtMotor;
    private javax.swing.JTextField txtPlaca;
    private javax.swing.JTextField txtPrecio;
    private javax.swing.JTextField txtPuerta;
    private javax.swing.JTextField txtbuscar;
    private javax.swing.JTextArea txtdesc;
    private javax.swing.JTextField txtidecarro;
    // End of variables declaration//GEN-END:variables
}
